services:
  api:
    build:
      context: ..
      dockerfile: .image/api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:5075
      ConnectionStrings__Ergonaut: Data Source=/data/sqlite/ergonaut.db
      Ergonaut__DataRoot: /data
      LogIngestion__Kafka__BootstrapServers: kafka:9092
    volumes:
      - ../config:/config:ro
      - ../data:/data
    ports:
      - "5075:5075"

  ui:
    build:
      context: ..
      dockerfile: .image/ui/Dockerfile
    depends_on:
      - api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:5242
      Api__BaseUrl: http://api:5075/
      Api__Auth__Username: dev
      Api__Auth__Password: dev
    volumes:
      - ../config:/config:ro
      - ../data-protection:/data-protection # Persisted data protection keys
    ports:
      - "5242:5242"

  sentinel:
    build:
      context: ..
      dockerfile: .image/sentinel/Dockerfile
    depends_on:
      - api
      - kafka
      - otelcol
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Api__BaseUrl: http://api:5075/
      Api__Auth__Username: dev
      Api__Auth__Password: dev
      LogIngestion__Kafka__BootstrapServers: kafka:9092
      ConnectionStrings__Ergonaut: Data Source=/data/sqlite/ergonaut.db
    volumes:
      - ../config:/config:ro
      - ../data:/data

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.85.0
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ../config/collector.yaml:/etc/otelcol/config.yaml
    ports:
      - "4318:4318"   # OTLP HTTP receiver
      - "4317:4317"   # OTLP gRPC receiver
      - "55681:55681" # OTLP HTTP receiver

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

